import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/accountcreation">AccountCreation</Link>
        </li>
        <li>
          <Link to="/advancedsearch">AdvancedSearch</Link>
        </li>
        <li>
          <Link to="/authenticationinwear">AuthenticationinWear</Link>
        </li>
        <li>
          <Link to="/calendar">Calendar</Link>
        </li>
        <li>
          <Link to="/contactsintegration">ContactsIntegration</Link>
        </li>
        <li>
          <Link to="/contactslist">ContactsList</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/discoverysettings">DiscoverySettings</Link>
        </li>
        <li>
          <Link to="/displayandtheme">Displayandtheme</Link>
        </li>
        <li>
          <Link to="/displaysettings">DisplaySettings</Link>
        </li>
        <li>
          <Link to="/emailsignin">EmailSignin</Link>
        </li>
        <li>
          <Link to="/employeelogin">Employeelogin</Link>
        </li>
        <li>
          <Link to="/facebooksigninone">FacebookSigninOne</Link>
        </li>
        <li>
          <Link to="/featuresettings">FeatureSettings</Link>
        </li>
        <li>
          <Link to="/compressfile">CompressFile</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/freetrial">FreeTrial</Link>
        </li>
        <li>
          <Link to="/hamburgermenu">HamburgerMenu</Link>
        </li>
        <li>
          <Link to="/facebooksignin">FacebookSignin</Link>
        </li>
        <li>
          <Link to="/keywordsearch">KeywordSearch</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
        <li>
          <Link to="/linkedinsignin">LinkedInSignin</Link>
        </li>
        <li>
          <Link to="/livechat">LiveChat</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/offlinework">Offlinework</Link>
        </li>
        <li>
          <Link to="/phonelogin">PhoneLogin</Link>
        </li>
        <li>
          <Link to="/promocodes">Promocodes</Link>
        </li>
        <li>
          <Link to="/radiostations">RadioStations</Link>
        </li>
        <li>
          <Link to="/settingsone">SettingsOne</Link>
        </li>
        <li>
          <Link to="/signin">Signin</Link>
        </li>
        <li>
          <Link to="/signuploginmodule">SignupLoginModule</Link>
        </li>
        <li>
          <Link to="/sorting">Sorting</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsAndConditions</Link>
        </li>
        <li>
          <Link to="/themes">Themes</Link>
        </li>
        <li>
          <Link to="/tutorials">Tutorials</Link>
        </li>
        <li>
          <Link to="/twofactorauthentication">Twofactorauthentication</Link>
        </li>
        <li>
          <Link to="/useravatar">UserAvatar</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
